version: "3.8"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:academy@pg-db:5432/mydb?schema=public
      - PORT=8080
      - JWT_SECRET=dVxrVKc8t8Z+B6Q9DrrdrkDl+CJUOqwBCBC5amTTXARUa51FSJK2QQgTDT+f3t631R6TyAo=
    ports:
      - 8080:8080
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - learnhub-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  learnhub-db-vol:
    name: bc1552d48e8c75194156a07517d2613fb839fec8126dd26faaa60199596d2a28
