version: "3.8"
services:
  api:
    # image: peetwerapat/be-project:ci.build-docker-image-
    build: .
    platform: linux/amd64

    environment:
      - DATABASE_URL=postgresql://postgres:academy@pg-db:5432/mydb?schema=public
      - PORT=8080
      - JWT_SECRET=dVxrVKc8t8Z+B6Q9DrrdrkDl+CJUOqwBCBC5amTTXARUa51FSJK2QQgTDT+f3t631R6TyAo=
      - REDIS_URL=redis://cache:6379
    ports:
      - 8080:8080
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cache:
    image: redis:7.2.3
    expose:
      - 6379
volumes:
  db-data:
