name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello-world
        run: echo "Hello world"
      - name: Where i am here?
        runn: pwd
      - name: Why
        run: ls
