name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello-world
        run: echo "Hello world"
      - name: Print out current directory
        run: pwd
      - name: Check out
        uses: actions/checkout@main
      - name: list file and directory
        run: ls
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
